### ISSUE TITLE
[BUG]: cannot convert number to u64 error while running Qwen3-30B-A3B

### ISSUE THREAD

**Issue by zhaoclaire** [ai-dynamo/dynamo#1094]
### Describe the Bug

ERROR dynamo_runtime::worker: Application shutdown with error: invalid operation: cannot convert number to u64 (in default:18)
Error: invalid operation: cannot convert number to u64 (in default:18)

### Steps to Reproduce

dynamo run out=vllm /usr/Qwen3-30B-A3B

### Expected Behavior

should run 

### Actual Behavior

does not run

### Environment

NA

**Comment by grahamking** [comment]
Caused by the Qwen3 prompt template doing something new. 

Fixed here by updating our `minijinja` dependency: https://github.com/ai-dynamo/dynamo/pull/1002

**Comment by zhaoclaire** [comment]
I updated `minijinja` to the latest version 2.10.2 but still getting this error 

```
ERROR dynamo_runtime::worker: Application shutdown with error: invalid operation: cannot convert number to u64 (in default:18)
Error: invalid operation: cannot convert number to u64 (in default:18)
Apptainer> pip list  | grep minijinja
minijinja                                    2.10.2
Apptainer> dynamo env 
System Information:
OS: Ubuntu 24.04
Glibc Version: 2.39
GCC Version: 13.3.0
Cmake Version: N/A
Rust Version: a
Docker Version: 26.1.3

CPU Information:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Address sizes:       46 bits physical, 57 bits virtual
Byte Order:          Little Endian
CPU(s):              32
Vendor ID:           GenuineIntel
Model name:          Intel(R) Xeon(R) Gold 6326 CPU @ 2.90GHz
CPU family:          6
Model:               106
Thread(s) per core:  1
Core(s) per socket:  16
Socket(s):           2
Stepping:            6
BogoMIPS:            5800.00

Python Version: 3.12.3
Python Platform: Linux-3.10.0-1160.119.1.el7.x86_64-x86_64-with-glibc2.39

Python Packages:
ai-dynamo: 0.2.0
ai-dynamo-runtime: 0.2.0
ai-dynamo-vllm: 0.8.4
genai-perf: Not installed
nixl: 0.2.1
numpy: 2.2.5
nvidia-cublas-cu12: 12.4.5.8
nvidia-cuda-cupti-cu12: 12.4.127
nvidia-cuda-nvrtc-cu12: 12.4.127
nvidia-cuda-runtime-cu12: 12.4.127
nvidia-cudnn-cu12: 9.1.0.70
nvidia-cufft-cu12: 11.2.1.3
nvidia-curand-cu12: 10.3.5.147
nvidia-cusolver-cu12: 11.6.1.9
nvidia-cusparse-cu12: 12.3.1.170
nvidia-ml-py: 12.575.51
nvidia-nccl-cu12: 2.21.5
nvidia-nvjitlink-cu12: 12.4.127
nvidia-nvtx-cu12: 12.4.127
pyzmq: 26.4.0
tensorrt_llm: Not installed
torch: 2.6.0
torchaudio: 2.6.0
transformers: 4.51.3
tritonclient: Not installed
```

**Comment by grahamking** [comment]
Qwen3 is not supported in the version of Dynamo you are using. You will need to pull latest code from the repo and build `dynamo-run` from source. Instructions here: https://github.com/ai-dynamo/dynamo/blob/main/docs/guides/dynamo_run.md#full-usage-details

That includes the fix I mentioned earlier.

I think Qwen3 support will be in the next release, 0.2.1, if you prefer to wait for that.

**Comment by zhaoclaire** [comment]
I see, thank you. Also curious when will the next release be

**Comment by grahamking** [comment]
> I see, thank you. Also curious when will the next release be

I'm not certain, but I think next week.
